# Copyright (c) 2025 Intel Corporation
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import warnings

import numpy as np
from optimum.intel.openvino import OVModelForCausalLM
from torch.jit import TracerWarning
from transformers import AutoTokenizer
from transformers import logging

from functools import partial
import numpy as np
import nncf
from nncf import Dataset
from datasets import load_dataset

import nncf

logging.set_verbosity_error()
warnings.filterwarnings("ignore", category=TracerWarning)


MODEL_ID = "meta-llama/Llama-3.1-8B-Instruct"
COMPRESSED_MODEL_ID = "Llama-3.1-8B-Instruct_hadamard"


def generate_answers(
    questions: list[str], model: OVModelForCausalLM, tokenizer: AutoTokenizer, max_new_tokens: int = 50
) -> dict[str, str]:
    """
    Generate answers for a list of questions using the provided model and tokenizer.

    :param questions: List of questions to be answered.
    :param model: The model to use for generating answers.
    :param tokenizer: The tokenizer to use for processing the input and output.
    :param max_new_tokens: Maximum number of new tokens to generate for each answer. Defaults to 50.
    :return: A dictionary mapping each question to its corresponding answer.
    """
    messages = [
        {"role": "system", "content": "You are a chatbot who always responds as short as possible."},
        {"role": "user", "content": "What is the capital of Spain?"},
        {"role": "assistant", "content": "Madrid."},
    ]
    answers_by_questions = {}

    for question in questions:
        messages.append({"role": "user", "content": question})
        input_ids = tokenizer.apply_chat_template(
            messages, tokenize=True, add_generation_prompt=True, return_tensors="pt"
        ).to(device=model.device)
        input_len = len(input_ids[0])

        output = model.generate(input_ids, max_new_tokens=max_new_tokens, do_sample=False)[0]
        answer = tokenizer.decode(output[input_len:], skip_special_tokens=True)
        answers_by_questions[question] = answer
        messages.append({"role": "assistant", "content": answer})

    return answers_by_questions


def print_answers(header: str, answers_by_questions: list[str]) -> None:
    """
    Print the answers to the console.

    :param header: Header to print before the answers.
    :param answers_by_questions: Dictionary mapping questions to their answers.
    """
    print(header)
    for question, answer in answers_by_questions.items():
        print(f"Q: {question}\nA: {answer}\n")


QUESTIONS = [
    "What is the capital of France?",
    "What is the highest peak in the Alps?",
    "What is the largest city in Canada?",
    "What is the most visited city in Japan?",
]


def load_model_and_tokenizer(model_id: str, export=True) -> tuple[OVModelForCausalLM, AutoTokenizer]:
    """
    Load the model and tokenizer from the specified model ID.

    :param model_id: The identifier of the model to load.
    :param export: Whether to export the model for OpenVINO. Defaults to True.
    :return: A tuple containing the loaded model and tokenizer.
    """
    tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=False)
    model = OVModelForCausalLM.from_pretrained(
        model_id,
        export=export,
        load_in_8bit=False,
    )
    return model, tokenizer


# example to prove that hadamard transform does not change inference results
def default_example(model_id: str, compressed_model_id: str) -> list[str]:
    """
    Example of using the default codebook compression.

    :param model_id: The identifier of the model to load.
    :param compressed_model_id: The identifier for the compressed model to save.
    :return: A list of answers generated by the model after compression.
    """
    model, tokenizer = load_model_and_tokenizer(model_id)
    answers_by_questions = generate_answers(QUESTIONS, model, tokenizer)
    print_answers("Non-optimized model outputs:\n", answers_by_questions)

    model.model = nncf.compress_weights(model.model, mode=nncf.CompressWeightsMode.INT8_SYM, ratio=1.0, hadamard=False)
    model.save_pretrained(compressed_model_id)
    tokenizer.save_pretrained(compressed_model_id)

    model, tokenizer = load_model_and_tokenizer(compressed_model_id, False)
    answers_by_questions = generate_answers(QUESTIONS, model, tokenizer)
    print_answers("Optimized model outputs:\n", answers_by_questions)

    return list(answers_by_questions.values())


# example to prove that hadamard transform does not change inference results
def example_hadamard(model_id: str, compressed_model_id: str, hadamard: bool=False) -> list[str]:
    """
    Example of using the default codebook compression.

    :param model_id: The identifier of the model to load.
    :param compressed_model_id: The identifier for the compressed model to save.
    :return: A list of answers generated by the model after compression.
    """
    model, tokenizer = load_model_and_tokenizer(model_id)
    nncf_dataset = get_nncf_dataset(model, tokenizer)

    gs = 128
    r = 1.0
    compressed_model_id = compressed_model_id + f"int4_had_{hadamard}_gs{gs}"

    model.model = nncf.compress_weights(
        model.model,
        mode=nncf.CompressWeightsMode.INT4_SYM,
        ratio=r,
        group_size=gs,
        dataset=nncf_dataset,
        scale_estimation = True,
        hadamard=hadamard,
        subset_size=8,
    )
    
    model.save_pretrained(compressed_model_id)
    tokenizer.save_pretrained(compressed_model_id)

    model, tokenizer = load_model_and_tokenizer(compressed_model_id, False)
    answers_by_questions = generate_answers(QUESTIONS, model, tokenizer)
    print_answers("Optimized model outputs:\n", answers_by_questions)

    return list(answers_by_questions.values())


def get_nncf_dataset(model, tokenizer):
    dataset = load_dataset('wikitext', 'wikitext-2-v1', split='train')
    dataset = dataset.filter(lambda example: len(example["text"]) > 128)

    def get_input_shapes(model, batch_size = 1):
        inputs = {}

        for val in model.model.inputs:
            name = val.any_name
            shape = list(val.partial_shape.get_min_shape())
            shape[0] = batch_size
            inputs[name] = shape

        return inputs
    
    def transform_func(item, tokenizer, input_shapes, ov_model, config, max_tokens=128):
        input_dtypes = {inp.get_any_name(): inp.get_element_type() for inp in ov_model.inputs}
        text = item['text']

        tokens = tokenizer(text)

        bad_tokens = tokenizer('<unk>')['input_ids']
        if len(bad_tokens) <= 2:
            raw_tokens = tokens['input_ids']
            filtered_tokens = np.array(list(filter(lambda x: x not in bad_tokens, raw_tokens)))
            
            tokens['input_ids'] = filtered_tokens
            tokens['attention_mask'] = tokens['attention_mask'][:filtered_tokens.shape[0]]
        
        res = {'input_ids': np.expand_dims(np.array(tokens['input_ids'][:max_tokens]), 0),
            'attention_mask': np.expand_dims(np.array(tokens['attention_mask'][:max_tokens]), 0)}

        if 'position_ids' in input_shapes:
            position_ids = np.cumsum(res['attention_mask'], axis=1) - 1
            position_ids[res['attention_mask'] == 0] = 1
            res['position_ids'] = position_ids

        batch_size = res['input_ids'].shape[0]
        if config.model_type == "bloom":
            batch_size *= config.num_attention_heads

        if "beam_idx" in input_shapes:
            res["beam_idx"] = np.arange(batch_size, dtype=int)

        for name, shape in input_shapes.items():
            if name in res:
                continue
            res[name] = ov.Tensor(shape=shape, type=input_dtypes[name])

        return res

    input_shapes = get_input_shapes(model)
    nncf_dataset = Dataset(dataset, partial(transform_func, tokenizer=tokenizer,
                                            input_shapes=input_shapes,
                                            ov_model=model.model,
                                            config=model.config))
    return nncf_dataset

def main():
    #default_example(MODEL_ID, COMPRESSED_MODEL_ID)
    example_hadamard(MODEL_ID, COMPRESSED_MODEL_ID, hadamard=True)
    example_hadamard(MODEL_ID, COMPRESSED_MODEL_ID, hadamard=False)


if __name__ == "__main__":
    main()
